In [1]:
import numpy as np

In [3]:
np.__version__

'2.2.4'

## Crear y Leer

### 1D Array

In [9]:
arr1 = np.array([1, 2, 3, 4, 5, 7]) #Creamos el array unidimensional.
arr1 #imprimimos el array.

array([1, 2, 3, 4, 5, 7])

In [10]:
type(arr1) #Función que nos devuelve el tipo de array.

numpy.ndarray

In [18]:
arr1.shape #Devuelve el número de elementos del array (6,) se utiliza la "," despues del cinco ya que lo devuelve como tupla y el formato lo dicta así. 

(6,)

In [19]:
arr1.dtype #Muestra el tipo de dato que conforma al array.

dtype('int64')

In [20]:
arr1.ndim #Muestra cuantas dimensiones tiene el array.

1

### 2D Array

In [33]:
arr2 = np.array([[1, 4, 5], [6, 7 ,4]]) #Creamos el array de dos dimensiones, lo cual es equivalente a juntar dos arrray unidimensonales (Fila y Columna)
arr2 #Imprimimos el array.

array([[1, 4, 5],
       [6, 7, 4]])

In [34]:
arr2.ndim #Devuelve el número de dimensiones, en este caso son 2.

2

In [35]:
arr2.shape #Devuelve el número de filas y columnas.

(2, 3)

In [36]:
arr2.dtype #Muestra el tipo de dato que conforma al array.

dtype('int64')

In [37]:
arr2.size #Devuelve el tamaño del array.

6

### 3D Array

In [50]:
arr3 = np.array([[[1, 4, 5], [6, 7 ,4]], [[3, 5, 6], [8,7,5]], [[1, 4, 5], [6, 7 ,4]]]) #Creamos el  array de 3 dimensiones.
arr3 #Imprimimos el array.

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 6],
        [8, 7, 5]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [51]:
arr3.ndim #Devuelve las dimensiones del array.

3

In [54]:
arr3.shape # Devuelve el número de arrays o layers(3), el número de filas por cada array(2) y el número de columnas(3) (3, 2, 3).

(3, 2, 3)

### Crear un array ramdon

In [56]:
randomArr = np.random.rand(3, 2, 3) # Los parametros a digitar serian los mismos utilizados en el metodo "shape".
randomArr #Imprimimos el array random.

array([[[0.20661616, 0.35458961, 0.63523221],
        [0.6578132 , 0.83723882, 0.05573072]],

       [[0.31414263, 0.25873152, 0.98645612],
        [0.24960908, 0.59025188, 0.9717243 ]],

       [[0.42243457, 0.40963781, 0.17140356],
        [0.13150887, 0.25485992, 0.14412979]]])

In [57]:
randomArr.dtype #Devuelve el tipo de dato dentro del array.

dtype('float64')

In [58]:
zeroes = np.zeros((3, 2, 3)) #Creamos un array compuesta por ceros.
zeroes #Imprimimos el array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [64]:
zeroes.ndim #Devuelve las dimensiones del array.

3

In [65]:
full = np.full((3, 2, 3), 9) #Creamos un array pero podemos darle aparte de las dimensiones el valor para rellenar el array (9) usando el metodo "full".
full #Imprimimos el array.

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [67]:
ones = np.ones((3, 2, 3))  #El metodo "ones" permite crear un array de las dimensiones deseadas con todos sus valores iguales a 1.
ones #Imprimimos el array.

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [69]:
arr3 #Llamamos nuevamente a nuestro array de tres dimensiones.

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 6],
        [8, 7, 5]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [83]:
#Jugamos con las posiciones de los arrays para obtener resultados especificos.
arr3[0] 

array([[1, 4, 5],
       [6, 7, 4]])

In [84]:
arr3[2, 1]

array([6, 7, 4])

In [85]:
arr3[0:2]

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 6],
        [8, 7, 5]]])

In [118]:
arr3[-1]

array([[1, 4, 5],
       [4, 6, 7]])

In [87]:
arr3 [1][0][1]

np.int64(5)

In [88]:
arr3 [1, 0, 1]

np.int64(5)

### Actualizar y Eliminar 

In [89]:
#Creamos dos arreglos randoms para trabajar estos temas.
a1 = np.random.rand(2, 3, 2)
a2 = np.random.rand(2, 3, 2)

In [90]:
a1 #Imprimos el array "a1"

array([[[0.40452854, 0.36767472],
        [0.20374763, 0.6609772 ],
        [0.33227938, 0.79570149]],

       [[0.13077222, 0.56420548],
        [0.63874622, 0.933665  ],
        [0.55567415, 0.52893937]]])

In [91]:
a2 #Imprimos el array "a2"

array([[[0.58955715, 0.19293777],
        [0.301225  , 0.69126371],
        [0.3927575 , 0.50633662]],

       [[0.39216138, 0.26278607],
        [0.32483276, 0.96778371],
        [0.1151331 , 0.41599201]]])

#### Operaciones Matemáticas Basicas

In [92]:
np.add(a1, a2) #Metodo para sumar dos arrays.

array([[[0.99408568, 0.56061249],
        [0.50497263, 1.35224091],
        [0.72503687, 1.30203811]],

       [[0.5229336 , 0.82699155],
        [0.96357898, 1.9014487 ],
        [0.67080725, 0.94493138]]])

In [95]:
np.subtract(a1, a2) #Metodo para restar dos arrays.

array([[[-0.18502861,  0.17473695],
        [-0.09747738, -0.03028651],
        [-0.06047812,  0.28936486]],

       [[-0.26138915,  0.3014194 ],
        [ 0.31391346, -0.03411871],
        [ 0.44054104,  0.11294737]]])

In [97]:
np.multiply(a1, a2) #Metodo para multiplicar dos arrays.

array([[[0.23849269, 0.07093834],
        [0.06137388, 0.45690955],
        [0.13050522, 0.40289281]],

       [[0.05128381, 0.14826534],
        [0.2074857 , 0.90358577],
        [0.06397649, 0.22003455]]])

In [96]:
np.divide(a1, a2)#Metodo para dividir dos arrays.

array([[[0.68615662, 1.90566483],
        [0.67639679, 0.95618675],
        [0.84601664, 1.57148713]],

       [[0.33346533, 2.14701438],
        [1.96638486, 0.96474552],
        [4.82636296, 1.27151331]]])

### Operaciones Estadisticas

In [99]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2,8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [100]:
sqrt

np.float64(5.0)

In [101]:
abs

np.int64(2)

In [102]:
power

np.int64(256)

In [103]:
log

np.float64(3.2188758248682006)

In [104]:
mins

np.float64(0.13077222222590557)

In [105]:
maxs

np.float64(0.9677837078503786)

#### Actualizar Arrays

In [106]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 6],
        [8, 7, 5]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [107]:
arr3[0, 0, 2] = 500 #Para actualizar digitamos las coordenadas del valor que queremos editar y le asignamos el valor que querramos.
arr3

array([[[  1,   4, 500],
        [  6,   7,   4]],

       [[  3,   5,   6],
        [  8,   7,   5]],

       [[  1,   4,   5],
        [  6,   7,   4]]])

In [110]:
arr3.sort() #Con el metodo "sort", es un metodo famoso para el ordenamiento de arrays.
arr3

array([[[  1,   4, 500],
        [  4,   6,   7]],

       [[  3,   5,   6],
        [  5,   7,   8]],

       [[  1,   4,   5],
        [  4,   6,   7]]])

In [111]:
arr3.shape

(3, 2, 3)

In [116]:
arr3_reshape = arr3.reshape((2,3,-1)) #Con el metodo "reshape" podemos modificar la forma del array, el "-1" es para calcular automaticamente el número de elementos que deberia tener la matriz
arr3_reshape

array([[[  1,   4, 500],
        [  4,   6,   7],
        [  3,   5,   6]],

       [[  5,   7,   8],
        [  1,   4,   5],
        [  4,   6,   7]]])

In [119]:
arr3_reshape.shape

(2, 3, 3)

### Añadir e Insertar

In [122]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [123]:
new_array = np.ones((3, 2, 3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [128]:
appd = np.append(zeroes, new_array, axis=0) #axus 0 = filam axis 1 = columna el metodo "append" permite añadir arrays.
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [129]:
#Insertar
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [130]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [134]:
inserted_array = np.insert(zeroes, 0, new_array, axis=0)
inserted_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

### Eliminar

In [140]:
array4 = np.random.rand(3, 2, 3)
array4

array([[[0.81335863, 0.33922615, 0.25901439],
        [0.6909382 , 0.74255228, 0.03610778]],

       [[0.99291417, 0.81043986, 0.37605216],
        [0.42848443, 0.24367164, 0.48685642]],

       [[0.02856597, 0.12303168, 0.4066784 ],
        [0.56559879, 0.42388454, 0.42486476]]])

In [141]:
# Eliminar el array
arr5 = np.delete(array4, 0, axis=1)

In [142]:
arr5

array([[[0.6909382 , 0.74255228, 0.03610778]],

       [[0.42848443, 0.24367164, 0.48685642]],

       [[0.56559879, 0.42388454, 0.42486476]]])

In [143]:
np.save("new array", arr5)

In [145]:
np.load("new array.npy")

array([[[0.6909382 , 0.74255228, 0.03610778]],

       [[0.42848443, 0.24367164, 0.48685642]],

       [[0.56559879, 0.42388454, 0.42486476]]])